sudo: false

cache:
  directories:
    - $HOME/.composer/cache

language: php

php:
  - 8.0
  - 7.4
  - 7.3
  - 7.2
  - 7.1

before_script:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --colors=always
